name: embed2scale-solution
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - timm
  - einops
  - rasterio
  - pyproj
  - pytorch-cuda=11.8
  - ca-certificates
  - openssl
  - torchgeo
  - certifi
  - xarray
  - zarr
